name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  registry: ghcr.io
  image: mankianer/gutenachtbot
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Extract version from tag
          run: |
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "repoImageName=${{env.registry}}/${{env.image}}" >> $GITHUB_ENV

        - name: Set up image names
          run: |
            echo "fullImageName=${{env.repoImageName}}:${{env.version}}" >> $GITHUB_ENV

        - name: Set up image names 2
          run: |
            echo "fullImageNameARM=${{env.repoImageName}}:arm64-${{env.version}}" >> $GITHUB_ENV
            echo "fullImageNameAMD=${{env.repoImageName}}:amd64-${{env.version}}" >> $GITHUB_ENV

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'

        - name: build-jar
          run: ./gradlew -Prelease.useLastTag=true final

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.registry }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and Push Image
          run: |
            docker buildx  build . -t ${{env.fullImageNameARM}} --push --platform linux/arm64
            docker buildx  build . -t ${{env.fullImageNameAMD}} --push --platform linux/amd64
        - name: Create Version Manifest
          run: |
            docker manifest create ${{env.fullImageName}} ${{env.fullImageNameARM}} ${{env.fullImageNameAMD}}
            docker manifest push ${{env.fullImageName}}
        - name: tag Manifest to latest
          run: |
            docker manifest tag ${{env.fullImageName}} ${{env.repoImageName}}:latest
            docker manifest push ${{env.repoImageName}}:latest